name: Drivewriter
version: ${project.version}
main: net.lordofthecraft.gitlab.drivewriter.Drivewriter
authors: [SeventhCircle]
description: A plugin for converting Gdocs into MC books
website: https://www.lordofthecraft.net
api-version: 1.13

commands:
  drivewriter:
    description: convert gdocs into mc books
    aliases: dw

permissions:
  drivewriter.use:
    description: Gives the ability to use drivewriter
