name: Drivewriter
version: 1.0.0
main: net.lordofthecraft.gitlab.drivewriter.Drivewriter
authors: [SeventhCircle]
description: A plugin for converting Gdocs into MC books
website: https://www.lordofthecraft.net

commands:
  drivewriter:
    description: convert gdocs into mc books
  dw:
    description: convert gdocs into mc books
permissions:
  drivewriter.use:
    description: Gives the ability to use drivewriter
